/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logined.QuanLyGianHang;

import EntityClass.Hang;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class ThemHang extends javax.swing.JPanel {

    /**
     * Creates new form ThemHang
     */
    public ThemHang(int page) {
        initComponents();
        this.page = page;
    }
    private int page;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtGiaGoc = new javax.swing.JTextField();
        txtKhuyenMai = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtViTri = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtMaSP = new javax.swing.JTextField();
        txtPhanLoai = new javax.swing.JComboBox<>();
        txtDonVi = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnNhapLai = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel3.setText("Quản Lý Gian Hàng/ Thêm Hàng");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tên Sản Phẩm:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Đơn Vị:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Phân Loại:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Giá Gốc:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Khuyến Mãi (%):");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Vị Trí:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Số Lượng:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Mã SP:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        txtGiaGoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtGiaGoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 140, -1));

        txtKhuyenMai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 100, -1));

        txtTenSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenSP.setEnabled(false);
        add(txtTenSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 480, -1));

        txtViTri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtViTri, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 140, -1));

        txtSoLuong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 140, -1));

        txtMaSP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMaSP.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtMaSPCaretUpdate(evt);
            }
        });
        add(txtMaSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 140, -1));

        txtPhanLoai.setEditable(true);
        txtPhanLoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPhanLoai.setEnabled(false);
        add(txtPhanLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 230, -1));

        txtDonVi.setEditable(true);
        txtDonVi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtDonVi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Test", "Test2" }));
        txtDonVi.setEnabled(false);
        add(txtDonVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 230, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("VND");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("%");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, -1, -1));

        btnNhapLai.setBackground(new java.awt.Color(13, 138, 254));
        btnNhapLai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNhapLai.setText("Nhập lại");
        btnNhapLai.setToolTipText("");
        btnNhapLai.setPreferredSize(new java.awt.Dimension(80, 28));
        btnNhapLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapLaiActionPerformed(evt);
            }
        });
        add(btnNhapLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, -1, -1));

        btnBack.setBackground(new java.awt.Color(234, 107, 72));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("< Back");
        btnBack.setToolTipText("");
        btnBack.setPreferredSize(new java.awt.Dimension(80, 28));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 710, -1, -1));

        btnThem.setBackground(new java.awt.Color(13, 138, 254));
        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.setToolTipText("");
        btnThem.setPreferredSize(new java.awt.Dimension(80, 28));
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        ((JLayeredPane)this.getParent()).add(new Home(page), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 770));
        this.setVisible(false);
        ((JLayeredPane)this.getParent()).remove(this);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnNhapLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapLaiActionPerformed
        // TODO add your handling code here:
        txtMaSP.setText("");
        txtTenSP.setText("");
        txtDonVi.setSelectedItem("");
        txtPhanLoai.setSelectedItem("");
        txtGiaGoc.setText("");
        txtKhuyenMai.setText("");
        txtViTri.setText("");
        txtSoLuong.setText("");
    }//GEN-LAST:event_btnNhapLaiActionPerformed

    private void txtMaSPCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtMaSPCaretUpdate
        // TODO add your handling code here:
        Hang hangMatchMaSP = Connection.ConnectHang.Instance().getHangChuaLenGianHangByMaSP(txtMaSP.getText());
        txtTenSP.setText(hangMatchMaSP.getTenSP());
        txtDonVi.setSelectedItem(hangMatchMaSP.getDonVi());
        txtPhanLoai.setSelectedItem(hangMatchMaSP.getPhanLoai());
        txtGiaGoc.setText("");
        txtKhuyenMai.setText("");
        txtViTri.setText("");
        txtSoLuong.setText("");
    }//GEN-LAST:event_txtMaSPCaretUpdate

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        Hang hangToAdd = Connection.ConnectHang.Instance().getHangChuaLenGianHangByMaSP(txtMaSP.getText());
        Object[] options = {"OK"};
        try {
            if(hangToAdd.getMaSP() != null){
                int giaGoc = Integer.parseInt(txtGiaGoc.getText());
                float khuyenMai = Float.parseFloat(txtKhuyenMai.getText());
                int soLuong = Integer.parseInt(txtSoLuong.getText());
                if( soLuong > hangToAdd.getSoLuongTonKho()){
                    JOptionPane.showOptionDialog(null,
                    "Số lượng cần nhập lên Gian Hang("+txtSoLuong.getText()+") > SL trong Kho ("+hangToAdd.getSoLuongTonKho()+")","Thông báo",
                    JOptionPane.PLAIN_MESSAGE,
                    JOptionPane.ERROR_MESSAGE,
                    null,
                    options,
                    options[0]);
                return;
                }
                if(0.0 > khuyenMai || khuyenMai > 100.0 ){
                    JOptionPane.showOptionDialog(null,
                    "Nhập Khuyến Mại trong Khoảng [0-100]","Thông báo",
                    JOptionPane.PLAIN_MESSAGE,
                    JOptionPane.ERROR_MESSAGE,
                    null,
                    options,
                    options[0]);
                    return;
                }
                if(txtViTri.getText().equals("")){
                    JOptionPane.showOptionDialog(null,
                    "Trường Vị Trí Còn Trống !","Thông báo",
                    JOptionPane.PLAIN_MESSAGE,
                    JOptionPane.ERROR_MESSAGE,
                    null,
                    options,
                    options[0]);
                    return;
                }
                if(giaGoc - giaGoc*khuyenMai/100 < hangToAdd.getGiaNhap()){
                    System.out.println(giaGoc - giaGoc*khuyenMai/100);
                    int result = JOptionPane.showConfirmDialog(null, "Giá Bán * Khuyến Mại("+(giaGoc - giaGoc*khuyenMai/100)+") đang nhỏ hơn Giá Nhập vào("+hangToAdd.getGiaNhap()+"),\n Bạn có chắc chắn?", "Thông báo", JOptionPane.YES_NO_OPTION);
                    if(result == JOptionPane.YES_OPTION){
                        hangToAdd.setSoLuongTonKho(hangToAdd.getSoLuongTonKho() - soLuong);
                        hangToAdd.setViTriGianHang(txtViTri.getText());
                        hangToAdd.setGiaBan(giaGoc);
                        hangToAdd.setKhuyenMai(khuyenMai/100);System.out.println(khuyenMai/100);
                        hangToAdd.setSoLuongGianHang(soLuong);
                        JOptionPane.showOptionDialog(null,
                        Connection.ConnectHang.Instance().addHangTuKhoLenGianHang(hangToAdd),"Thông báo",
                        JOptionPane.PLAIN_MESSAGE,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        options[0]);
                        return;
                    }
                    else
                        return;
                }
                //Unless have any If Case, run this
                hangToAdd.setSoLuongTonKho(hangToAdd.getSoLuongTonKho() - soLuong);
                hangToAdd.setViTriGianHang(txtViTri.getText());
                hangToAdd.setGiaBan(giaGoc);
                hangToAdd.setKhuyenMai(khuyenMai/100);System.out.println(khuyenMai/100);
                hangToAdd.setSoLuongGianHang(soLuong);
                JOptionPane.showOptionDialog(null,
                Connection.ConnectHang.Instance().addHangTuKhoLenGianHang(hangToAdd),"Thông báo",
                JOptionPane.PLAIN_MESSAGE,
                JOptionPane.INFORMATION_MESSAGE,
                null,
                options,
                options[0]);
            }
            else{
                JOptionPane.showOptionDialog(null,
                "Không có mặt hàng mã: '" + txtMaSP.getText() + "' trong Kho !","Thông báo",
                JOptionPane.PLAIN_MESSAGE,
                JOptionPane.ERROR_MESSAGE,
                null,
                options,
                options[0]);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showOptionDialog(null,
            "Kiểm tra lại Giá Gốc, Khuyến Mại, Số Lượng (Phải là Số)","Thông báo",
            JOptionPane.PLAIN_MESSAGE,
            JOptionPane.ERROR_MESSAGE,
            null,
            options,
            options[0]);
        }catch (Exception e){
            JOptionPane.showOptionDialog(null,
            e,"Thông báo",
            JOptionPane.PLAIN_MESSAGE,
            JOptionPane.ERROR_MESSAGE,
            null,
            options,
            options[0]);
        }
 
    }//GEN-LAST:event_btnThemActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNhapLai;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> txtDonVi;
    private javax.swing.JTextField txtGiaGoc;
    private javax.swing.JTextField txtKhuyenMai;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JComboBox<String> txtPhanLoai;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtViTri;
    // End of variables declaration//GEN-END:variables
}
