package MainPackage;


import Logined.LoginedPanel;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        PaneDangNhap.setVisible(false);
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Layer = new javax.swing.JLayeredPane();
        NotLoginPanel = new javax.swing.JPanel();
        PaneDangNhap = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();
        btnXemKhuyenMai = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachSanPham = new javax.swing.JTable();
        btnHienThiPaneDangNhap = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbKetQua = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbTongSanPham = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnPrev = new javax.swing.JButton();
        lblTrangHienTai = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quản Lý Siêu Thị");

        Layer.setPreferredSize(new java.awt.Dimension(1024, 768));
        Layer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NotLoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        NotLoginPanel.setForeground(new java.awt.Color(255, 255, 255));
        NotLoginPanel.setMinimumSize(new java.awt.Dimension(1024, 768));
        NotLoginPanel.setPreferredSize(new java.awt.Dimension(1024, 768));
        NotLoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PaneDangNhap.setBackground(new java.awt.Color(58, 161, 207));
        PaneDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        PaneDangNhap.setPreferredSize(new java.awt.Dimension(450, 217));
        PaneDangNhap.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Đăng Nhập sử dụng tài khoản ACC SPM");
        PaneDangNhap.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("User");
        PaneDangNhap.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Password");
        PaneDangNhap.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        btnDangNhap.setBackground(new java.awt.Color(38, 58, 88));
        btnDangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng Nhập");
        btnDangNhap.setPreferredSize(new java.awt.Dimension(140, 30));
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });
        PaneDangNhap.add(btnDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        btnHuy.setBackground(new java.awt.Color(234, 107, 72));
        btnHuy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHuy.setForeground(new java.awt.Color(255, 255, 255));
        btnHuy.setText("Hủy");
        btnHuy.setPreferredSize(new java.awt.Dimension(140, 30));
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        PaneDangNhap.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        txtUser.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PaneDangNhap.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 380, -1));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        txtPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PaneDangNhap.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 380, -1));

        NotLoginPanel.add(PaneDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 338, 455, -1));

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NotLoginPanel.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 630, -1));

        btnTim.setBackground(new java.awt.Color(13, 138, 254));
        btnTim.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTim.setForeground(new java.awt.Color(255, 255, 255));
        btnTim.setText("Tìm");
        btnTim.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnTim.setPreferredSize(new java.awt.Dimension(75, 25));
        btnTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimActionPerformed(evt);
            }
        });
        NotLoginPanel.add(btnTim, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 170, -1, -1));

        btnXemKhuyenMai.setBackground(new java.awt.Color(13, 138, 254));
        btnXemKhuyenMai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXemKhuyenMai.setForeground(new java.awt.Color(255, 255, 255));
        btnXemKhuyenMai.setText("Xem Khuyến Mãi");
        btnXemKhuyenMai.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnXemKhuyenMai.setPreferredSize(new java.awt.Dimension(133, 25));
        btnXemKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemKhuyenMaiActionPerformed(evt);
            }
        });
        NotLoginPanel.add(btnXemKhuyenMai, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 170, -1, -1));

        btnRefresh.setBackground(new java.awt.Color(255, 255, 255));
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/RoofSPM_BUTTON.png"))); // NOI18N
        btnRefresh.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnRefresh.setPreferredSize(new java.awt.Dimension(1024, 215));
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        NotLoginPanel.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1024, 450));

        tblDanhSachSanPham.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblDanhSachSanPham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblDanhSachSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDanhSachSanPham.setFocusable(false);
        tblDanhSachSanPham.setRowHeight(25);
        tblDanhSachSanPham.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tblDanhSachSanPham.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tblDanhSachSanPham.getTableHeader().setReorderingAllowed(false);
        tblDanhSachSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachSanPhamMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachSanPham);

        NotLoginPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));

        btnHienThiPaneDangNhap.setBackground(new java.awt.Color(13, 138, 254));
        btnHienThiPaneDangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHienThiPaneDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnHienThiPaneDangNhap.setText("Đăng Nhập");
        btnHienThiPaneDangNhap.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnHienThiPaneDangNhap.setPreferredSize(new java.awt.Dimension(160, 35));
        btnHienThiPaneDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHienThiPaneDangNhapActionPerformed(evt);
            }
        });
        NotLoginPanel.add(btnHienThiPaneDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(806, 721, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Hiển thị kết quả từ");

        lbKetQua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbKetQua.setText("1-20");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("trong tổng số");

        lbTongSanPham.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTongSanPham.setText("4321");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("sản phẩm.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbKetQua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbTongSanPham)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(0, 365, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbKetQua)
                    .addComponent(jLabel4)
                    .addComponent(lbTongSanPham)
                    .addComponent(jLabel6)))
        );

        NotLoginPanel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, 720, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnPrev.setBackground(new java.awt.Color(13, 138, 254));
        btnPrev.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(255, 255, 255));
        btnPrev.setText("Trang trước");
        btnPrev.setBorder(null);
        btnPrev.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnPrev.setPreferredSize(new java.awt.Dimension(80, 25));
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        lblTrangHienTai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTrangHienTai.setText("Trang 0");

        btnNext.setBackground(new java.awt.Color(13, 138, 254));
        btnNext.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Trang sau");
        btnNext.setBorder(null);
        btnNext.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnNext.setMaximumSize(new java.awt.Dimension(75, 17));
        btnNext.setMinimumSize(new java.awt.Dimension(75, 17));
        btnNext.setPreferredSize(new java.awt.Dimension(80, 25));
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTrangHienTai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTrangHienTai)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        NotLoginPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 670, 290, 50));

        Layer.add(NotLoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(Layer, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadData(){
       TableHang table = new TableHang(Connection.ConnectHang.Instance().getDataGianHang());
       table.setPage(currentPage - 1);
       lbTongSanPham.setText(String.valueOf(table.getSumOfProduct()));
       lblTrangHienTai.setText("Trang " + table.getPage());
       lbKetQua.setText(table.getRangeOfCurrentPage());
       currentPage = table.getPage();
       tblDanhSachSanPham.setModel(table);
       
       StyleTheTable();
    }
    private void loadSearchData(){
       TableHang table = new TableHang(Connection.ConnectHang.Instance().getDataSearchGuest(txtSearch.getText(), false));
       table.setPage(currentPage - 1);
       lbTongSanPham.setText(String.valueOf(table.getSumOfProduct()));
       lblTrangHienTai.setText("Trang " + table.getPage());
       lbKetQua.setText(table.getRangeOfCurrentPage());
       currentPage = table.getPage();
       tblDanhSachSanPham.setModel(table);
       
       StyleTheTable();
    }
    private void loadSeeDiscountData(){
       TableHang table = new TableHang(Connection.ConnectHang.Instance().getDataSearchGuest(txtSearch.getText(), true));
       table.setPage(currentPage - 1);
       lbTongSanPham.setText(String.valueOf(table.getSumOfProduct()));
       lblTrangHienTai.setText("Trang " + table.getPage());
       lbKetQua.setText(table.getRangeOfCurrentPage());
       currentPage = table.getPage();
       tblDanhSachSanPham.setModel(table);
       
       StyleTheTable();
    }
    private void StyleTheTable(){
        //Change Header Color
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        Color darkerLightBlue = new Color(13, 138, 254);
        headerRenderer.setBackground(darkerLightBlue);
        headerRenderer.setForeground(Color.WHITE);
        headerRenderer.setPreferredSize(new Dimension(WIDTH, 30));
        for (int i = 0; i < tblDanhSachSanPham.getColumnCount(); i++) {
            tblDanhSachSanPham.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        //Change Row Color
        tblDanhSachSanPham.setDefaultRenderer(Object.class, new DefaultTableCellRenderer()
        {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column)
            {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                Color lightBlue = new Color(189,215,238);
                Color darkerLightBlue = new Color(13, 138, 254);
                c.setBackground(row % 2 == 0 ? lightBlue : Color.WHITE);
                if (isSelected) {
                    c.setBackground(darkerLightBlue);
                    c.setForeground(Color.white);
                }
                else {
                    c.setForeground(Color.BLACK);
                }
                return c;
            }
        });
    }
    private void btnHienThiPaneDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHienThiPaneDangNhapActionPerformed
        // TODO add your handling code here:
        PaneDangNhap.setVisible(true);
        tblDanhSachSanPham.setEnabled(false);
        btnRefresh.setEnabled(false);
        btnPrev.setEnabled(false);
        btnNext.setEnabled(false);
        btnTim.setEnabled(false);
        btnXemKhuyenMai.setEnabled(false);
        txtSearch.setEnabled(false);
        btnHienThiPaneDangNhap.setEnabled(false);
    }//GEN-LAST:event_btnHienThiPaneDangNhapActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        PaneDangNhap.setVisible(false);
        tblDanhSachSanPham.setEnabled(true);
        btnRefresh.setEnabled(true);
        btnPrev.setEnabled(true);
        btnNext.setEnabled(true);
        btnTim.setEnabled(true);
        btnXemKhuyenMai.setEnabled(true);
        txtSearch.setEnabled(true);
        btnHienThiPaneDangNhap.setEnabled(true);
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        Layer.remove(NotLoginPanel);
        Layer.add(new LoginedPanel(), new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1024, 768));
        Layer.repaint();
        Layer.revalidate();
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        currentPage++;
        if(isSearching)
            loadSearchData();
        else if(isSeeingDiscount)
            loadSeeDiscountData();
        else
            loadData();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        currentPage--;
        if(isSearching)
            loadSearchData();
        else if(isSeeingDiscount)
            loadSeeDiscountData();
        else
            loadData();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void tblDanhSachSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachSanPhamMouseClicked
        // TODO add your handling code here:
 
    }//GEN-LAST:event_tblDanhSachSanPhamMouseClicked

    private void btnTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimActionPerformed
        // TODO add your handling code here:
       isSearching = true;
       isSeeingDiscount = false;
       currentPage = 1;
       loadSearchData();
    }//GEN-LAST:event_btnTimActionPerformed

    private void btnXemKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemKhuyenMaiActionPerformed
        // TODO add your handling code here:
       isSeeingDiscount = true;
       isSearching = false;
       currentPage = 1;
       loadSeeDiscountData();
    }//GEN-LAST:event_btnXemKhuyenMaiActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        currentPage = 1;
        loadData();
        isSearching = false;
        isSeeingDiscount = false;
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame jframe = new MainFrame();
                jframe.setVisible(true);
                jframe.setLocationRelativeTo(null);
                
                //new MainFrame().setVisible(true);
            }
        });
    }
    private boolean isSearching = false,isSeeingDiscount = false;
    private int currentPage = 1;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane Layer;
    private javax.swing.JPanel NotLoginPanel;
    private javax.swing.JPanel PaneDangNhap;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnHienThiPaneDangNhap;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btnXemKhuyenMai;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbKetQua;
    private javax.swing.JLabel lbTongSanPham;
    private javax.swing.JLabel lblTrangHienTai;
    private javax.swing.JTable tblDanhSachSanPham;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
